---
abstract: 'Device and library agnostic graphic primitives'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphics-Primitive
no_index:
  directory:
    - inc
    - t
requires:
  Forest: 0.04
  Geometry::Primitive: 0.13
  Graphics::Color: 0.16
  Moose: 0.54
  MooseX::AttributeHelpers: 0.12
  MooseX::Clone: 0.03
  MooseX::Storage: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.36
